#ifndef ATTRIBUTE_H
#define ATTRIBUTE_H

#include <vector>
#include <string>
#include <map>

namespace Belzebub {

enum class Attribute {
    NoAttribute = -101,

    //Rare: position 0, 2, 4, 6
    //Crafted: position 0-3
    EvenMana = 0, EvenEnhancedArmor, EvenChanceToHit, EvenEnhancedDamage, EvenAddsFireDamage, EvenAddsLightningDamage,
    EvenResistMagic, EvenResistFire, EvenResistLightning, EvenResistCold, EvenResistAll,
    EvenSpellsLevels, EvenIncreasedCharges, EvenCriticalHitChance,
    EvenSpellPower, EvenMagicItemsChance, EvenAddSpell, EvenIncreasedArmor,
    EvenMaximumResistMagic, EvenMaximumResistFire, EvenMaximumResistLightning, EvenMaximumResistCold, EvenMaximumResistAll,

    //Rare: position 1, 3, 5, 7
    //Crafted: position 4-7
    OddStrength, OddMagic, OddDexterity, OddVitality, OddAllAttributes,
    OddHitPoints, OddAddsPointsToDamage, OddDamageTakenFromEnemies,
    OddAddsFireDamage, OddAddsLightningDamage, OddAddsColdDamage,
    OddHitStealsLife, OddHitStealsMana, OddCriticalHitDamage, OddLightRadiusIncreased,
    OddAttackSpeed, OddHitRecoverySpeed,
    OddLowDurability, OddHighDurability, OddIndestructible, OddKnockback, OddBlockSpeed,
    OddRegeneratesLife, OddRegeneratesMana, OddCastingSpeed,
    OddAbsorbsHalfTrapDamage, OddAttackerTakesDamage,
    OddHalfFreezeDuration, OddChanceToKnockback,
    OddStrength2, OddMagic2, OddDexterity2, OddVitality2, OddHitPoints2,
    OddAddsPointsToDamage2, OddDamageTakenFromEnemies2, OddHitRecoverySpeed2, OddAttackerTakesDamage2,
    OddAddsFireDamage2, OddAddsLightningDamage2, OddAddsColdDamage2,
    OddTargetFireResistance, OddTargetLightningResistance, OddTargetColdResistance, OddTargetMagicResistance,
    OddCannotBeFrozen,

    //Unique
    UniqueStrength, UniqueMagic, UniqueDexterity, UniqueVitality, UniqueAllAttributes,
    UniqueArmorClass, UniqueIncreasedArmor, UniqueEnhancedArmor, UniqueChanceToHit, UniqueEnhancedDamage, UniqueAddPointsToDamage,
    UniqueLightningHitDamage, UniqueFireHitDamage, UniqueColdHitDamage, UniqueMagicHitDamage,
    UniqueResistAll, UniqueResistFire, UniqueResistLightning, UniqueResistMagic, UniqueResistCold, UniqueAllResistancesZero,
    UniqueRegeneratesLife, UniqueRegeneratesMana, UniqueFasterHitRecovery,
    UniqueIncreasedAttackSpeed, UniqueFasterBlockRate, UniqueFasterWalk, UniqueIncreasedCastSpeed, UniqueLightRadius,
    UniqueDamageTakenFromEnemies, UniqueHitPoints, UniqueMana,
    UniqueHighDurability, UniqueAlteredDurability, UniqueIndestructible, UniqueSpellLevels,
    UniqueHitStealsLife, UniqueHitStealsMana,
    UniqueRequirements, UniqueOneHandedWeapon, UniqueUnusualItemDamage, UniqueChanceToKnockback,
    UniqueDamageVsDemon, UniqueDamageVsUndead,
    UniqueSpellCharges,
    UniqueCriticalHitChance, UniqueCriticalHitDamage, UniqueSpellPower,
    UniqueExtraGold, UniqueMagicItemsChance,
    UniqueHalfTrapDamage, UniqueAttackerTakesDamage, UniqueIncreasedChanceOfBlocking,
    UniqueTargetResistances, UniqueTargetPhysicalResistances,
    UniqueTargetFireResistance, UniqueTargetLightningResistance, UniqueTargetColdResistance, UniqueTargetMagicResistance,
    UniquePiercingAttack, UniqueHalfFreezeDuration, UniqueCannotBeFrozen,
    UniqueMaximumMana, UniqueMaximumLife,
    UniqueHitPointsCharacterLevel, UniqueManaCharacterLevel,
    UniqueStrengthCharacterLevel,UniqueDexterityCharacterLevel, UniqueMagicCharacterLevel, UniqueVitalityCharacterLevel, UniqueAllStatsCharacterLevel,
    UniqueToHitCharacterLevel, UniqueDamageCharacterLevel, UniqueSpellPowerCharacterLevel,
    UniqueDamageVsDemonsCharacterLevel, UniqueDamageVsUndeadCharacterLevel, UniqueAddsDamageCharacterLevel, UniqueArmorClassCharacterLevel,
    UniqueResistAllCharacterLevel,
    UniqueFireDamageCharacterLevel, UniqueLightningDamageCharacterLevel, UniqueColdDamageCharacterLevel, UniqueMagicDamageCharacterLevel,
    UniqueMagicItemsChanceCharacterLevel, UniqueExtraGoldCharacterLevel,
    UniqueMaximumResistAll, UniqueMaximumResistFire, UniqueMaximumResistLightning, UniqueMaximumResistMagic, UniqueMaximumResistCold,
    UniqueAddSpell, UniqueActOfTransformation, UniqueDamageAbsorbedByMana,
    UniqueChanceToCastSpellOnStriking, UniqueChanceToCastSpellWhenStruck,
    UniqueIgnoreTargetDefense,

    //Set (not same as Unique)
    SetStrength, SetMagic, SetDexterity, SetVitality, SetAllAttributes,
    SetArmorClass, SetIncreasedArmor, SetEnhancedArmor, SetChanceToHit, SetEnhancedDamage, SetAddPointsToDamage,
    SetLightningHitDamage, SetFireHitDamage, SetColdHitDamage, SetMagicHitDamage,
    SetResistAll, SetResistFire, SetResistLightning, SetResistMagic, SetResistCold, SetAllResistancesZero,
    SetRegeneratesLife, SetRegeneratesMana,
    SetIncreasedChanceOfBlocking, SetFasterHitRecovery, SetIncreasedAttackSpeed, SetFasterBlockRate,
    SetFasterWalk, SetIncreasedCastSpeed, SetLightRadius, SetDamageTakenFromEnemies,
    SetHitPoints, SetMana,
    SetHighDurability, SetAlteredDurability, SetIndestructible,
    SetSpellLevels, SetHitStealsLife, SetHitStealsMana,
    SetRequirements, SetOneHandedWeapon, SetOffhandWeapon, SetChanceToKnockback, SetDamageVsDemon, SetDamageVsUndead,
    SetCriticalHitChance, SetCriticalHitDamage, SetSpellPower,
    SetExtraGold, SetMagicItemsChance,
    SetHalfTrapDamage, SetAttackerTakesDamage,
    SetTargetResistances, SetTargetPhysicalResistances,
    SetTargetFireResistance, SetTargetLightningResistance, SetTargetColdResistance, SetTargetMagicResistance,
    SetPiercingAttack, SetHalfFreezeDuration, SetCannotBeFrozen,
    SetMaximumMana, SetMaximumLife,
    SetHitPointsCharacterLevel, SetManaCharacterLevel,
    SetStrengthCharacterLevel,SetDexterityCharacterLevel, SetMagicCharacterLevel, SetVitalityCharacterLevel, SetAllStatsCharacterLevel,
    SetToHitCharacterLevel, SetDamageCharacterLevel, SetSpellPowerCharacterLevel,
    SetDamageVsDemonsCharacterLevel, SetDamageVsUndeadCharacterLevel, SetAddsDamageCharacterLevel, SetArmorClassCharacterLevel,
    SetResistAllCharacterLevel,
    SetFireDamageCharacterLevel, SetLightningDamageCharacterLevel, SetColdDamageCharacterLevel, SetMagicDamageCharacterLevel,
    SetMagicItemsChanceCharacterLevel, SetExtraGoldCharacterLevel,
    SetMaximumResistAll, SetMaximumResistFire, SetMaximumResistLightning, SetMaximumResistMagic, SetMaximumResistCold,
    SetAddSpell, SetActOfTransformation, SetDamageAbsorbedByMana,
    SetChanceToCastSpellOnStriking, SetChanceToCastSpellWhenStruck,
    SetIgnoreTargetDefense,
};
enum class AttributeMode {Even, Odd, Unique, Set};

constexpr int ValueOff = -500;
constexpr int ValueSpell = -501;
constexpr int ValueMinus1 = -502;
constexpr int ValuePlus1 = -503;

struct AttributeData {
    AttributeMode mode;
    int start = -1;
    int end = -1;
    std::string name;
    int value1Min = ValueOff;
    int value1Max = ValueOff;
    int value2Min = ValueOff;
    int value2Max = ValueOff;
    Attribute attribute = Attribute::NoAttribute;
};
const std::map<Attribute, AttributeData> attrMap = {
    {Attribute::NoAttribute, {AttributeMode::Even, (int)Attribute::NoAttribute, (int)Attribute::NoAttribute, "No Attribute"}},

    {Attribute::EvenMana, {AttributeMode::Even, 0, 9, "Mana : +X", -125, 32000}},
    {Attribute::EvenEnhancedArmor, {AttributeMode::Even, 10, 21, "+X% Enhanced Armor", -125, 32000}},
    {Attribute::EvenChanceToHit, {AttributeMode::Even, 22, 44, "Chance To Hit : +X%", -125, 32000}},
    {Attribute::EvenEnhancedDamage, {AttributeMode::Even, 45, 57, "+X% Enhanced Damage", -125, 32000}},
    {Attribute::EvenAddsFireDamage, {AttributeMode::Even, 58, 58, "Adds X To Y Fire Damage", 1, 32000, 1, 32000}},
    {Attribute::EvenAddsLightningDamage, {AttributeMode::Even, 59, 59, "Adds X To Y Lightning Damage", 1, 32000, 1, 32000}},
    {Attribute::EvenResistMagic, {AttributeMode::Even, 60, 64, "Resist Magic : +X%", -125, 60}},
    {Attribute::EvenResistFire, {AttributeMode::Even, 65, 69, "Resist Fire : +X%", -125, 60}},
    {Attribute::EvenResistLightning, {AttributeMode::Even, 70, 74, "Resist Lightning : +X%", -125, 60}},
    {Attribute::EvenResistCold, {AttributeMode::Even, 75, 79, "Resist Cold : +X%", -125, 60}},
    {Attribute::EvenResistAll, {AttributeMode::Even, 80, 84, "Resist All : +X%", -125, 60}},
    {Attribute::EvenSpellsLevels, {AttributeMode::Even, 85, 88, "Spells Are Increased X Levels", -10, 10}},
    {Attribute::EvenIncreasedCharges, {AttributeMode::Even, 89, 90, "IncreasedCharges", 1, 32000}},
    {Attribute::EvenCriticalHitChance, {AttributeMode::Even, 91, 96, "Critical Hit Chance : +X%", 1, 32000}},
    {Attribute::EvenSpellPower, {AttributeMode::Even, 97, 103, "+X% Spell Power", 1, 32000}},
    {Attribute::EvenMagicItemsChance, {AttributeMode::Even, 104, 109, "+X% Chance Of Getting Magic Items", -125, 32000}},
    {Attribute::EvenAddSpell, {AttributeMode::Even, 110, 115, "+Y To Spell (X)", ValueSpell, ValueSpell, 1, 10}},
    {Attribute::EvenIncreasedArmor, {AttributeMode::Even, 116, 127, "Increased Armor: +X", 1, 32000}},
    {Attribute::EvenMaximumResistMagic, {AttributeMode::Even, 128, 129, "Maximum Resist Magic : +X%", -125, 25}},
    {Attribute::EvenMaximumResistFire, {AttributeMode::Even, 130, 131, "Maximum Resist Fire: +X%", -125, 25}},
    {Attribute::EvenMaximumResistLightning, {AttributeMode::Even, 132, 133, "Maximum Resist Lightning: +X%", -125, 25}},
    {Attribute::EvenMaximumResistCold, {AttributeMode::Even, 134, 135, "Maximum Resist Cold: +X%", -125, 25}},
    {Attribute::EvenMaximumResistAll, {AttributeMode::Even, 136, 137, "Maximum Resist All: +X%", -125, 25}},

    {Attribute::OddStrength, {AttributeMode::Odd, 0, 6, "+X To Strength", -125, 32000}},
    {Attribute::OddMagic, {AttributeMode::Odd, 7, 13, "+X To Magic", -125, 32000}},
    {Attribute::OddDexterity, {AttributeMode::Odd, 14, 20, "+X To Dexterity", -125, 32000}},
    {Attribute::OddVitality, {AttributeMode::Odd, 21, 27, "+X To Vitality", -125, 32000}},
    {Attribute::OddAllAttributes, {AttributeMode::Odd, 28, 34, "+X To All Attributes", -125, 32000}},
    {Attribute::OddHitPoints, {AttributeMode::Odd, 35, 44, "Hit Points : +X", -125, 32000}},
    {Attribute::OddAddsPointsToDamage, {AttributeMode::Odd, 45, 50, "Adds X Points To Damage", -125, 32000}},
    {Attribute::OddDamageTakenFromEnemies, {AttributeMode::Odd, 51, 57, "-X Damage Taken From Enemies", -125, 32000}},
    {Attribute::OddAddsFireDamage, {AttributeMode::Odd, 58, 61, "Adds X To Y Fire Damage", 1, 32000, 1, 32000}},
    {Attribute::OddAddsLightningDamage, {AttributeMode::Odd, 62, 65, "Adds X To Y Lightning Damage", 1,  32000, 1, 32000}},
    {Attribute::OddAddsColdDamage, {AttributeMode::Odd, 66, 69, "Adds X To Y Cold Damage", 1, 32000, 1, 32000}},
    {Attribute::OddHitStealsLife, {AttributeMode::Odd, 70, 74, "Hit Steals X% Life", 1, 30}},
    {Attribute::OddHitStealsMana, {AttributeMode::Odd, 75, 79, "Hit Steals X% Mana", 1, 30}},
    {Attribute::OddCriticalHitDamage, {AttributeMode::Odd, 80, 85, "Critical Hit Damage : +X%", 1, 32000}},
    {Attribute::OddLightRadiusIncreased, {AttributeMode::Odd, 86, 89, "Light Radius Increased/Decreased By X%", -125, 125}},
    {Attribute::OddAttackSpeed, {AttributeMode::Odd, 90, 93, "Attack Speed : +X%", 1, 32000}},
    {Attribute::OddHitRecoverySpeed, {AttributeMode::Odd, 94, 96, "Hit Recovery Speed : +X%", 1, 32000}},
    {Attribute::OddLowDurability, {AttributeMode::Odd, 97, 98, "Low Durability"}},
    {Attribute::OddHighDurability, {AttributeMode::Odd, 99, 103, "High Durability"}},
    {Attribute::OddIndestructible, {AttributeMode::Odd, 104, 104, "Indestructible"}},
    {Attribute::OddKnockback, {AttributeMode::Odd, 105, 105, "Knockback"}},
    {Attribute::OddBlockSpeed, {AttributeMode::Odd, 106, 106, "Block Speed : +X%", 1, 32000}},
    {Attribute::OddRegeneratesLife, {AttributeMode::Odd, 107, 109, "Regenerates X Life Per 5 Sec", 1, 125}},
    {Attribute::OddRegeneratesMana, {AttributeMode::Odd, 110, 112, "Regenerates X Mana Per 5 Sec", 1, 125}},
    {Attribute::OddCastingSpeed, {AttributeMode::Odd, 113, 114, "Casting Speed : +X%", 1, 30}},
    {Attribute::OddAbsorbsHalfTrapDamage, {AttributeMode::Odd, 115, 115, "Absorbs Half Trap Damage"}},
    {Attribute::OddAttackerTakesDamage, {AttributeMode::Odd, 116, 116, "Attacker Takes X - Y Damage"}},
    {Attribute::OddHalfFreezeDuration, {AttributeMode::Odd, 117, 118, "Half Freeze Duration"}},
    {Attribute::OddChanceToKnockback, {AttributeMode::Odd, 119, 121, "+X% Chance To Knockback", 1, 32000}},
    {Attribute::OddStrength2, {AttributeMode::Odd, 122, 122, "+X To Strength (2)", -125, 32000}},
    {Attribute::OddMagic2, {AttributeMode::Odd, 123, 123, "+X To Magic (2)", -125, 32000}},
    {Attribute::OddDexterity2, {AttributeMode::Odd, 124, 124, "+X To Dexterity (2)", -125, 32000}},
    {Attribute::OddVitality2, {AttributeMode::Odd, 125, 125, "+X To Vitality (2)", -125, 32000}},
    {Attribute::OddHitPoints2, {AttributeMode::Odd, 126, 126, "Hit Points : +X", -125, 32000}},
    {Attribute::OddAddsPointsToDamage2, {AttributeMode::Odd, 127, 128, "Adds X Points To Damage (2)", -125, 32000}},
    {Attribute::OddDamageTakenFromEnemies2, {AttributeMode::Odd, 129, 129, "-X Damage Taken From Enemies (2)", -125, 32000}},
    {Attribute::OddHitRecoverySpeed2, {AttributeMode::Odd, 130, 130, "Hit Recovery Speed : +X% (2)", 1, 32000}},
    {Attribute::OddAttackerTakesDamage2, {AttributeMode::Odd, 131, 133, "Attacker Takes X - Y Damage (2)", 1, 32000, 1, 32000}},
    {Attribute::OddAddsFireDamage2, {AttributeMode::Odd, 134, 134, "Adds X To Y Fire Damage (2)", 1, 32000, 1, 32000}},
    {Attribute::OddAddsLightningDamage2, {AttributeMode::Odd, 135, 135, "Adds X To Y Lightning Damage (2)", 1, 32000, 1, 32000}},
    {Attribute::OddAddsColdDamage2, {AttributeMode::Odd, 136, 136, "Adds X To Y Cold Damage (2)", 1, 32000, 1, 32000}},
    {Attribute::OddTargetFireResistance, {AttributeMode::Odd, 137, 141, "Target Fire Resistance: -X%", -125, -1}},
    {Attribute::OddTargetLightningResistance, {AttributeMode::Odd, 142, 146, "Target Lightning Resistance: -X%", -125, -1}},
    {Attribute::OddTargetColdResistance, {AttributeMode::Odd, 147, 151, "Target Cold Resistance: -X%", -125, -1}},
    {Attribute::OddTargetMagicResistance, {AttributeMode::Odd, 152, 156, "Target Magic Resistance: -X%", -125, -1}},
    {Attribute::OddCannotBeFrozen, {AttributeMode::Odd, 157, 157, "Cannot Be Frozen"}},

    {Attribute::UniqueStrength, {AttributeMode::Unique, 1, 1, "+X To Strength", -125, 32000}},
    {Attribute::UniqueMagic, {AttributeMode::Unique, 2, 2, "+X To Magic", -125, 32000}},
    {Attribute::UniqueDexterity, {AttributeMode::Unique, 3, 3, "+X To Dexterity", -125, 32000}},
    {Attribute::UniqueVitality, {AttributeMode::Unique, 4, 4, "+X To Vitality", -125, 32000}},
    {Attribute::UniqueAllAttributes, {AttributeMode::Unique, 5, 5, "+X To All Attributes", -125, 32000}},
    {Attribute::UniqueArmorClass, {AttributeMode::Unique, 6, 6, "Armor Class: X", -125, 32000}},
    {Attribute::UniqueIncreasedArmor, {AttributeMode::Unique, 7, 7, "Increased Armor: X", -125, 32000}},
    {Attribute::UniqueEnhancedArmor, {AttributeMode::Unique, 8, 8, "+X% Enhanced Armor", -125, 32000}},
    {Attribute::UniqueChanceToHit, {AttributeMode::Unique, 9, 9, "Chance To Hit +X%", -125, 32000}},
    {Attribute::UniqueEnhancedDamage, {AttributeMode::Unique, 10, 10, "+X% Enhanced Damage", -125, 32000}},
    {Attribute::UniqueAddPointsToDamage, {AttributeMode::Unique, 11, 11, "Adds X Points To Damage", 1, 32000}},
    {Attribute::UniqueLightningHitDamage, {AttributeMode::Unique, 12, 12, "Lightning Hit Damage : X To Y", 1, 32000, 1, 32000}},
    {Attribute::UniqueFireHitDamage, {AttributeMode::Unique, 13, 13, "Fire Hit Damage : X To Y", 1, 32000, 1, 32000}},
    {Attribute::UniqueColdHitDamage, {AttributeMode::Unique, 14, 14, "Cold Hit Damage : X To Y", 1, 32000, 1, 32000}},
    {Attribute::UniqueMagicHitDamage, {AttributeMode::Unique, 15, 15, "Magic Hit Damage : X To Y", 1, 32000, 1, 32000}},
    {Attribute::UniqueResistAll, {AttributeMode::Unique, 16, 16, "Resist All : +X%", -125, 60}},
    {Attribute::UniqueResistFire, {AttributeMode::Unique, 17, 17, "Resist Fire : +X%", -125, 60}},
    {Attribute::UniqueResistLightning, {AttributeMode::Unique, 18, 18, "Resist Lightning : +X%", -125, 60}},
    {Attribute::UniqueResistMagic, {AttributeMode::Unique, 19, 19, "Resist Magic : +X%", -125, 60}},
    {Attribute::UniqueResistCold, {AttributeMode::Unique, 20, 20, "Resist Cold : +X%", -125, 60}},
    {Attribute::UniqueAllResistancesZero, {AttributeMode::Unique, 21, 21, "All Resistances Equals 0%"}},
    {Attribute::UniqueRegeneratesLife, {AttributeMode::Unique, 22, 22, "Regenerates X Life Per 5 Sec", 1, 125}},
    {Attribute::UniqueRegeneratesMana, {AttributeMode::Unique, 23, 23, "Regenerates X Mana Per 5 Sec", 1, 125}},
    {Attribute::UniqueFasterHitRecovery, {AttributeMode::Unique, 24, 24, "X% Faster Hit Recovery", 1, 32000}},
    {Attribute::UniqueIncreasedAttackSpeed, {AttributeMode::Unique, 25, 25, "X% Increased Attack Speed", 1, 32000}},
    {Attribute::UniqueFasterBlockRate, {AttributeMode::Unique, 26, 26, "X% Faster Block Rate", 1, 32000}},
    {Attribute::UniqueFasterWalk, {AttributeMode::Unique, 27, 27, "X% Faster Walk", 1, 32000}},
    {Attribute::UniqueIncreasedCastSpeed, {AttributeMode::Unique, 28, 28, "X% Increased Cast Speed", 1, 30}},
    {Attribute::UniqueLightRadius, {AttributeMode::Unique, 29, 29, "+X% Light Radius", -125, 125}},
    {Attribute::UniqueDamageTakenFromEnemies, {AttributeMode::Unique, 30, 30, "-X Damage Taken From Enemies", -125, 125}},
    {Attribute::UniqueHitPoints, {AttributeMode::Unique, 31, 31, "Hit Points : +X", -125, 32000}},
    {Attribute::UniqueMana, {AttributeMode::Unique, 32, 32, "Mana : +X", -125, 32000}},
    {Attribute::UniqueHighDurability, {AttributeMode::Unique, 33, 33, "High Durability", ValuePlus1, ValuePlus1}},
    {Attribute::UniqueAlteredDurability, {AttributeMode::Unique, 34, 34, "Altered Durability", ValuePlus1, ValuePlus1}},
    {Attribute::UniqueIndestructible, {AttributeMode::Unique, 35, 35, "Indestructible", ValuePlus1, ValuePlus1}},
    {Attribute::UniqueSpellLevels, {AttributeMode::Unique, 36, 36, "Spells Are Increased X Levels", -10, 10}},
    {Attribute::UniqueHitStealsLife, {AttributeMode::Unique, 37, 37, "Hit Steals X% Life", 1, 30}},
    {Attribute::UniqueHitStealsMana, {AttributeMode::Unique, 38, 38, "Hit Steals X% Mana", 1, 30}},
    {Attribute::UniqueRequirements, {AttributeMode::Unique, 39, 39, "Requirements +X%", -100, 100}},
    {Attribute::UniqueOneHandedWeapon, {AttributeMode::Unique, 40, 40, "One Handed Weapon", ValuePlus1, ValuePlus1}},
    {Attribute::UniqueUnusualItemDamage, {AttributeMode::Unique, 41, 41, "Unusual Item Damage", 1, 32000}},
    {Attribute::UniqueChanceToKnockback, {AttributeMode::Unique, 42, 42, "X% Change To Knockback", 1, 32000}},
    {Attribute::UniqueDamageVsDemon, {AttributeMode::Unique, 43, 43, "X% Damage Vs. Demon", 1, 32000}},
    {Attribute::UniqueDamageVsUndead, {AttributeMode::Unique, 44, 44, "X% Damage Vs. Undead", 1, 32000}},
    {Attribute::UniqueSpellCharges, {AttributeMode::Unique, 45, 45, "Spell (X) Charges (Y)", ValueSpell, ValueSpell, 1, 32000}},
    {Attribute::UniqueCriticalHitChance, {AttributeMode::Unique, 47, 47, "+X% Critical Hit Chance", 1, 32000}},
    {Attribute::UniqueCriticalHitDamage, {AttributeMode::Unique, 48, 48, "+X% Critical Hit Damage", 1, 32000}},
    {Attribute::UniqueSpellPower, {AttributeMode::Unique, 49, 49, "+X% Spell Power", 1, 32000}},
    {Attribute::UniqueExtraGold, {AttributeMode::Unique, 50, 50, "+X% Extra Gold From Monsters", 1, 32000}},
    {Attribute::UniqueMagicItemsChance, {AttributeMode::Unique, 51, 51, "+X% Chance Of Getting Magic Items", -125, 32000}},
    {Attribute::UniqueHalfTrapDamage, {AttributeMode::Unique, 52, 52, "Absorbs Half Trap Damage", ValuePlus1, ValuePlus1}},
    {Attribute::UniqueAttackerTakesDamage, {AttributeMode::Unique, 53, 53, "Attacker Takes X - Y Damage", 1, 32000, 1, 32000}},
    {Attribute::UniqueIncreasedChanceOfBlocking, {AttributeMode::Unique, 54, 54, "X% Increased Chance Of Blocking", 1, 32000}},
    {Attribute::UniqueTargetResistances, {AttributeMode::Unique, 55, 55, "Reduces Target Resistances: X%", -125, -1}},
    {Attribute::UniqueTargetPhysicalResistances, {AttributeMode::Unique, 56, 56, "Reduces Target Physical Resistance: X%", -125, -1}},
    {Attribute::UniqueTargetFireResistance, {AttributeMode::Unique, 57, 57, "Reduces Target Fire Resistance: X%", -125, -1}},
    {Attribute::UniqueTargetLightningResistance, {AttributeMode::Unique, 58, 58, "Reduces Target Lightning Resistance: X%", -125, -1}},
    {Attribute::UniqueTargetColdResistance, {AttributeMode::Unique, 59, 59, "Reduces Target Cold Resistance: X%", -125, -1}},
    {Attribute::UniqueTargetMagicResistance, {AttributeMode::Unique, 60, 60, "Reduces Target Magic Resistance: X%", -125, -1}},
    {Attribute::UniquePiercingAttack, {AttributeMode::Unique, 61, 61, "Piercing Attack: X%", 1, 32000}},
    {Attribute::UniqueHalfFreezeDuration, {AttributeMode::Unique, 62, 62, "Half Freeze Duration", ValuePlus1, ValuePlus1}},
    {Attribute::UniqueCannotBeFrozen, {AttributeMode::Unique, 63, 63, "Cannot Be Frozen", ValuePlus1, ValuePlus1}},
    {Attribute::UniqueMaximumMana, {AttributeMode::Unique, 64, 64, "Increased Maximum Mana X%", 1, 30}},
    {Attribute::UniqueMaximumLife, {AttributeMode::Unique, 65, 65, "Increased Maximum Life X%", 1, 30}},
    {Attribute::UniqueHitPointsCharacterLevel, {AttributeMode::Unique, 66, 66, "Hit Points : +(L*X/Y) (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueManaCharacterLevel, {AttributeMode::Unique, 67, 67, "Mana : +(L*X/Y) (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueStrengthCharacterLevel, {AttributeMode::Unique, 68, 68, "+(L*X/Y) To Strength (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueDexterityCharacterLevel, {AttributeMode::Unique, 69, 69, "+(L*X/Y) To Dexterity (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueMagicCharacterLevel, {AttributeMode::Unique, 70, 70, "+(L*X/Y) To Magic (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueVitalityCharacterLevel, {AttributeMode::Unique, 71, 71, "+(L*X/Y) To Vitality (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueAllStatsCharacterLevel, {AttributeMode::Unique, 72, 72, "+(L*X/Y) To All Stats. (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::UniqueToHitCharacterLevel, {AttributeMode::Unique, 73, 73, "To Hit : (L*X/Y)% (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueDamageCharacterLevel, {AttributeMode::Unique, 74, 74, "+(L*X/Y)% Damage (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueSpellPowerCharacterLevel, {AttributeMode::Unique, 75, 75, "+(L*X/Y)% Spell Power (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueDamageVsDemonsCharacterLevel, {AttributeMode::Unique, 76, 76, "+(L*X/Y)% Damage Vs.Demons (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueDamageVsUndeadCharacterLevel, {AttributeMode::Unique, 77, 77, "+(L*X/Y)% Damage Vs.Undead (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueAddsDamageCharacterLevel, {AttributeMode::Unique, 78, 78, "Adds (L*X/Y) Damage (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueArmorClassCharacterLevel, {AttributeMode::Unique, 79, 79, "+(L*X/Y) To Armor Class (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueResistAllCharacterLevel, {AttributeMode::Unique, 80, 80, "Resist All : +(L*X/Y)% (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueFireDamageCharacterLevel, {AttributeMode::Unique, 81, 81, "+(L*X/Y)/2-(L*X/Y) Fire Damage (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueLightningDamageCharacterLevel, {AttributeMode::Unique, 82, 82, "+1-(L*X/Y) Lightning Damage (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueColdDamageCharacterLevel, {AttributeMode::Unique, 83, 83, "+(L*X/Y)/2-(L*X/Y) Cold Damage (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueMagicDamageCharacterLevel, {AttributeMode::Unique, 84, 84, "+(L*X/Y)/2-(L*X/Y) Magic Damage (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueMagicItemsChanceCharacterLevel, {AttributeMode::Unique, 85, 85, "+(L*X/Y)% Chance Of Getting Magic Items (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueExtraGoldCharacterLevel, {AttributeMode::Unique, 86, 86, "+(L*X/Y)% Extra Gold From Monsters (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::UniqueMaximumResistAll, {AttributeMode::Unique, 87, 87, "Maximum Resist All : +X%", -125, 25}},
    {Attribute::UniqueMaximumResistFire, {AttributeMode::Unique, 88, 88, "Maximum Resist Fire : +X%", -125, 25}},
    {Attribute::UniqueMaximumResistLightning, {AttributeMode::Unique, 89, 89, "Maximum Resist Lightning : +X%", -125, 25}},
    {Attribute::UniqueMaximumResistMagic, {AttributeMode::Unique, 90, 90, "Maximum Resist Magic : +X%", -125, 25}},
    {Attribute::UniqueMaximumResistCold, {AttributeMode::Unique, 91, 91, "Maximum Resist Cold : +X%", -125, 25}},
    {Attribute::UniqueAddSpell, {AttributeMode::Unique, 92, 92, "+Y To Spell (X)", ValueSpell, ValueSpell, -10, 10}},
    {Attribute::UniqueActOfTransformation, {AttributeMode::Unique, 99, 99, "Act Of Transformation (X)", 1, 32000, 0, 127}},
    {Attribute::UniqueDamageAbsorbedByMana, {AttributeMode::Unique, 100, 100, "X% Damage Absorbed By Mana", 1, 30}},
    {Attribute::UniqueChanceToCastSpellOnStriking, {AttributeMode::Unique, 101, 101, "Y% Chance To Cast Spell (Y) On Striking", ValueSpell, ValueSpell, 1, 100}},
    {Attribute::UniqueChanceToCastSpellWhenStruck, {AttributeMode::Unique, 102, 102, "Y% Chance To Cast Spell (Y) When Struck", ValueSpell, ValueSpell, 1, 100}},
    {Attribute::UniqueIgnoreTargetDefense, {AttributeMode::Unique, 103, 103, "Ignore Target's Defense", ValuePlus1, ValuePlus1}},

    {Attribute::SetStrength, {AttributeMode::Set, 1, 1, "+X To Strength", -125, 32000}},
    {Attribute::SetMagic, {AttributeMode::Set, 2, 2, "+X To Magic", -125, 32000}},
    {Attribute::SetDexterity, {AttributeMode::Set, 3, 3, "+X To Dexterity", -125, 32000}},
    {Attribute::SetVitality, {AttributeMode::Set, 4, 4, "+X To Vitality", -125, 32000}},
    {Attribute::SetAllAttributes, {AttributeMode::Set, 5, 5, "+X To All Attributes", -125, 32000}},
    {Attribute::SetArmorClass, {AttributeMode::Set, 6, 6, "Armor Class: X", -125, 32000}},
    {Attribute::SetIncreasedArmor, {AttributeMode::Set, 7, 7, "Increased Armor: X", -125, 32000}},
    {Attribute::SetEnhancedArmor, {AttributeMode::Set, 8, 8, "+X% Enhanced Armor", -125, 32000}},
    {Attribute::SetChanceToHit, {AttributeMode::Set, 9, 9, "Chance To Hit +X%", -125, 32000}},
    {Attribute::SetEnhancedDamage, {AttributeMode::Set, 10, 10, "+X% Enhanced Damage", -125, 32000}},
    {Attribute::SetAddPointsToDamage, {AttributeMode::Set, 11, 11, "Adds X Points To Damage", -125, 32000}},
    {Attribute::SetLightningHitDamage, {AttributeMode::Set, 12, 12, "Lightning Hit Damage : X To Y", 1, 32000, 1, 32000}},
    {Attribute::SetFireHitDamage, {AttributeMode::Set, 13, 13, "Fire Hit Damage : X To Y", 1, 32000, 1, 32000}},
    {Attribute::SetColdHitDamage, {AttributeMode::Set, 14, 14, "Cold Hit Damage : X To Y", 1, 32000, 1, 32000}},
    {Attribute::SetMagicHitDamage, {AttributeMode::Set, 15, 15, "Magic Hit Damage : X To Y", 1, 32000, 1, 32000}},
    {Attribute::SetResistAll, {AttributeMode::Set, 16, 16, "Resist All : +X%", -125, 60}},
    {Attribute::SetResistFire, {AttributeMode::Set, 17, 17, "Resist Fire : +X%", -125, 60}},
    {Attribute::SetResistLightning, {AttributeMode::Set, 18, 18, "Resist Lightning : +X%", -125, 60}},
    {Attribute::SetResistMagic, {AttributeMode::Set, 19, 19, "Resist Magic : +X%", -125, 60}},
    {Attribute::SetResistCold, {AttributeMode::Set, 20, 20, "Resist Cold : +X%", -125, 60}},
    {Attribute::SetAllResistancesZero, {AttributeMode::Set, 21, 21, "All Resistances Equals 0%"}},
    {Attribute::SetRegeneratesLife, {AttributeMode::Set, 22, 22, "Regenerates X Life Per 5 Sec", 1, 125}},
    {Attribute::SetRegeneratesMana, {AttributeMode::Set, 23, 23, "Regenerates X Mana Per 5 Sec", 1, 125}},
    {Attribute::SetIncreasedChanceOfBlocking, {AttributeMode::Set, 24, 24, "X% Increased Chance Of Blocking", 1, 32000}},
    {Attribute::SetFasterHitRecovery, {AttributeMode::Set, 25, 25, "X% Faster Hit Recovery", 1, 32000}},
    {Attribute::SetIncreasedAttackSpeed, {AttributeMode::Set, 26, 26, "X% Increased Attack Speed", 1, 32000}},
    {Attribute::SetFasterBlockRate, {AttributeMode::Set, 27, 27, "X% Faster Block Rate", 1, 32000}},
    {Attribute::SetFasterWalk, {AttributeMode::Set, 28, 28, "X% Faster Walk", 1, 32000}},
    {Attribute::SetIncreasedCastSpeed, {AttributeMode::Set, 29, 29, "X% Increased Cast Speed", 1, 30}},
    {Attribute::SetLightRadius, {AttributeMode::Set, 30, 30, "+X% Light Radius", -125, 125}},
    {Attribute::SetDamageTakenFromEnemies, {AttributeMode::Set, 31, 31, "-X Damage Taken From Enemies", -125, 32000}},
    {Attribute::SetHitPoints, {AttributeMode::Set, 32, 32, "Hit Points : +X", -125, 32000}},
    {Attribute::SetMana, {AttributeMode::Set, 33, 33, "Mana : +X", -125, 32000}},
    {Attribute::SetHighDurability, {AttributeMode::Set, 34, 34, "High Durability", ValuePlus1, ValuePlus1}},
    {Attribute::SetAlteredDurability, {AttributeMode::Set, 35, 35, "Altered Durability", ValuePlus1, ValuePlus1}},
    {Attribute::SetIndestructible, {AttributeMode::Set, 36, 36, "Indestructible", ValuePlus1, ValuePlus1}},
    {Attribute::SetSpellLevels, {AttributeMode::Set, 37, 37, "Spells Are Increased X Levels", -10, 10, ValueOff, ValueOff}},
    {Attribute::SetHitStealsLife, {AttributeMode::Set, 38, 38, "Hit Steals X% Life", 1, 30}},
    {Attribute::SetHitStealsMana, {AttributeMode::Set, 39, 39, "Hit Steals X% Mana", 1, 30}},
    {Attribute::SetRequirements, {AttributeMode::Set, 40, 40, "Requirements +X%", -100, 100}},
    {Attribute::SetOneHandedWeapon, {AttributeMode::Set, 41, 41, "One Handed Weapon", ValuePlus1, ValuePlus1}},
    {Attribute::SetOffhandWeapon, {AttributeMode::Set, 42, 42, "Offhand Weapon", ValuePlus1, ValuePlus1}},
    {Attribute::SetChanceToKnockback, {AttributeMode::Set, 43, 43, "X% Change To Knockback", 1, 100}},
    {Attribute::SetDamageVsDemon, {AttributeMode::Set, 44, 44, "X% Damage Vs. Demon", 1, 32000}},
    {Attribute::SetDamageVsUndead, {AttributeMode::Set, 45, 45, "X% Damage Vs. Undead", 1, 32000}},
    {Attribute::SetCriticalHitChance, {AttributeMode::Set, 48, 48, "+X% Critical Hit Chance", 1, 32000}},
    {Attribute::SetCriticalHitDamage, {AttributeMode::Set, 49, 49, "+X% Critical Hit Damage", 1, 32000}},
    {Attribute::SetSpellPower, {AttributeMode::Set, 50, 50, "+X% Spell Power", 1, 32000}},
    {Attribute::SetExtraGold, {AttributeMode::Set, 51, 51, "+X% Extra Gold From Monsters", 1, 32000}},
    {Attribute::SetMagicItemsChance, {AttributeMode::Set, 52, 52, "+X% Chance Of Getting Magic Items", -125, 32000}},
    {Attribute::SetHalfTrapDamage, {AttributeMode::Set, 53, 53, "Absorbs Half Trap Damage", ValuePlus1, ValuePlus1}},
    {Attribute::SetAttackerTakesDamage, {AttributeMode::Set, 54, 54, "Attacker Takes X - Y Damage", 1, 32000, 1, 32000}},
    {Attribute::SetTargetResistances, {AttributeMode::Set, 55, 55, "Reduces Target Resistances: X%", -125, -1}},
    {Attribute::SetTargetPhysicalResistances, {AttributeMode::Set, 56, 56, "Reduces Target Physical Resistance: X%", -125, -1}},
    {Attribute::SetTargetFireResistance, {AttributeMode::Set, 57, 57, "Reduces Target Fire Resistance: X%", -125, -1}},
    {Attribute::SetTargetLightningResistance, {AttributeMode::Set, 58, 58, "Reduces Target Lightning Resistance: X%", -125, -1}},
    {Attribute::SetTargetColdResistance, {AttributeMode::Set, 59, 59, "Reduces Target Cold Resistance: X%", -125, -1}},
    {Attribute::SetTargetMagicResistance, {AttributeMode::Set, 60, 60, "Reduces Target Magic Resistance: X%", -125, -1}},
    {Attribute::SetPiercingAttack, {AttributeMode::Set, 61, 61, "Piercing Attack: X%", 1, 32000}},
    {Attribute::SetHalfFreezeDuration, {AttributeMode::Set, 62, 62, "Half Freeze Duration", ValuePlus1, ValuePlus1}},
    {Attribute::SetCannotBeFrozen, {AttributeMode::Set, 63, 63, "Cannot Be Frozen", ValuePlus1, ValuePlus1}},
    {Attribute::SetMaximumMana, {AttributeMode::Set, 64, 64, "Increased Maximum Mana X%", 1, 30}},
    {Attribute::SetMaximumLife, {AttributeMode::Set, 65, 65, "Increased Maximum Life X%", 1, 30}},
    {Attribute::SetHitPointsCharacterLevel, {AttributeMode::Set, 66, 66, "Hit Points : +(L*X/Y) (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::SetManaCharacterLevel, {AttributeMode::Set, 67, 67, "Mana : +(L*X/Y) (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::SetStrengthCharacterLevel, {AttributeMode::Set, 68, 68, "+(L*X/Y) To Strength (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetDexterityCharacterLevel, {AttributeMode::Set, 69, 69, "+(L*X/Y) To Dexterity (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetMagicCharacterLevel, {AttributeMode::Set, 70, 70, "+(L*X/Y) To Magic (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetVitalityCharacterLevel, {AttributeMode::Set, 71, 71, "+(L*X/Y) To Vitality (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetAllStatsCharacterLevel, {AttributeMode::Set, 72, 72, "+(L*X/Y) To All Stats. (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetToHitCharacterLevel, {AttributeMode::Set, 73, 73, "To Hit : (L*X/Y)% (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetDamageCharacterLevel, {AttributeMode::Set, 74, 74, "+(L*X/Y)% Damage (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetSpellPowerCharacterLevel, {AttributeMode::Set, 75, 75, "+(L*X/Y)% Spell Power (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetDamageVsDemonsCharacterLevel, {AttributeMode::Set, 76, 76, "+(L*X/Y)% Damage Vs.Demons (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetDamageVsUndeadCharacterLevel, {AttributeMode::Set, 77, 77, "+(L*X/Y)% Damage Vs.Undead (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetAddsDamageCharacterLevel, {AttributeMode::Set, 78, 78, "Adds (L*X/Y) Damage (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetArmorClassCharacterLevel, {AttributeMode::Set, 79, 79, "+(L*X/Y) To Armor Class (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetResistAllCharacterLevel, {AttributeMode::Set, 80, 80, "Resist All : +(L*X/Y)% (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetFireDamageCharacterLevel, {AttributeMode::Set, 81, 81, "+(L*X/Y)/2-(L*X/Y) Fire Damage (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetLightningDamageCharacterLevel, {AttributeMode::Set, 82, 82, "+1-(L*X/Y) Lightning Damage (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetColdDamageCharacterLevel, {AttributeMode::Set, 83, 83, "+(L*X/Y)/2-(L*X/Y) Cold Damage (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetMagicDamageCharacterLevel, {AttributeMode::Set, 84, 84, "+(L*X/Y)/2-(L*X/Y) Magic Damage (Based On Character Level), 1, 4, 1, 4"}},
    {Attribute::SetMagicItemsChanceCharacterLevel, {AttributeMode::Set, 85, 85, "+(L*X/Y)% Chance Of Getting Magic Items (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::SetExtraGoldCharacterLevel, {AttributeMode::Set, 86, 86, "+(L*X/Y)% Extra Gold From Monsters (Based On Character Level)", 1, 4, 1, 4}},
    {Attribute::SetMaximumResistAll, {AttributeMode::Set, 87, 87, "Maximum Resist All : +X%", -125, 25}},
    {Attribute::SetMaximumResistFire, {AttributeMode::Set, 88, 88, "Maximum Resist Fire : +X%", -125, 25}},
    {Attribute::SetMaximumResistLightning, {AttributeMode::Set, 89, 89, "Maximum Resist Lightning : +X%", -125, 25}},
    {Attribute::SetMaximumResistMagic, {AttributeMode::Set, 90, 90, "Maximum Resist Magic : +X%", -125, 25}},
    {Attribute::SetMaximumResistCold, {AttributeMode::Set, 91, 91, "Maximum Resist Cold : +X%", -125, 25}},
    {Attribute::SetAddSpell, {AttributeMode::Set, 92, 92, "+Y To Spell (X)", ValueSpell, ValueSpell, -10, 10}},
    {Attribute::SetActOfTransformation, {AttributeMode::Set, 99, 99, "Act Of Transformation (X)", 1, 32000}},
    {Attribute::SetDamageAbsorbedByMana, {AttributeMode::Set, 100, 100, "X% Damage Absorbed By Mana", 1, 30}},
    {Attribute::SetChanceToCastSpellOnStriking, {AttributeMode::Set, 101, 101, "Y% Chance To Cast Spell (Y) On Striking", ValueSpell, ValueSpell, 1, 100}},
    {Attribute::SetChanceToCastSpellWhenStruck, {AttributeMode::Set, 102, 102, "Y% Chance To Cast Spell (Y) When Struck", ValueSpell, ValueSpell, 1, 100}},
    {Attribute::SetIgnoreTargetDefense, {AttributeMode::Set, 103, 103, "Ignore Target's Defense", ValuePlus1, ValuePlus1}},
};

}

#endif // ATTRIBUTE_H
