#ifndef ITEMTYPE_H
#define ITEMTYPE_H

#include <vector>
#include <string>

namespace Belzebub {

enum class ItemMagic {NoItem = 0, Quest = 7, Common = 8, Magic = 9, Rare = 10, Unique = 11, Set = 12, Crafted = 13};

enum ItemHelperType {Other, Staff};

struct ItemType {
    ItemHelperType type;
    int number;
    std::string name;
};

const std::vector<ItemType> itemTypes = {
    {ItemHelperType::Other, -1, "no type"},
    {ItemHelperType::Other, 0, "Healing Potion"},
    {ItemHelperType::Other, 1, "Mana Potion"},
    {ItemHelperType::Other, 2, "Rejuvation Potion"},
    {ItemHelperType::Other, 3, "Elixir Of Vitality"},
    {ItemHelperType::Other, 4, "Full Healing Potion"},
    {ItemHelperType::Other, 5, "Full Mana Potion"},
    {ItemHelperType::Other, 6, "Full Rejuvation Potion"},
    {ItemHelperType::Other, 7, "Elixir Of Strength"},
    {ItemHelperType::Other, 8, "Elixir Of Magic"},
    {ItemHelperType::Other, 9, "Elixir Of Dexterity"},
    {ItemHelperType::Other, 10, "Na Pot"},
    {ItemHelperType::Other, 11, "Na Pot"},
    {ItemHelperType::Other, 12, "Golden Elixir"},
    {ItemHelperType::Other, 13, "Soulstone"},
    {ItemHelperType::Other, 14, "Spectral Elixir"},
    {ItemHelperType::Other, 15, "Scroll"},
    {ItemHelperType::Other, 16, "Scroll"},
    {ItemHelperType::Other, 17, "Scroll"},
    {ItemHelperType::Other, 18, "Ear"},
    {ItemHelperType::Other, 19, "Ear"},
    {ItemHelperType::Other, 20, "Ear"},
    {ItemHelperType::Other, 21, "Heart"},
    {ItemHelperType::Other, 22, "Eye"},
    {ItemHelperType::Other, 23, "Demon's Brain"},
    {ItemHelperType::Other, 24, "Bloodstone"},
    {ItemHelperType::Other, 25, "empty"},
    {ItemHelperType::Other, 26, "empty"},
    {ItemHelperType::Other, 27, "empty"},
    {ItemHelperType::Other, 28, "Staff Of Lazarus"},
    {ItemHelperType::Other, 29, "The Magic Rock"},
    {ItemHelperType::Other, 30, "Black Mushroom"},
    {ItemHelperType::Other, 31, "Map Of The Stars"},
    {ItemHelperType::Other, 32, "Tavern's Sign"},
    {ItemHelperType::Other, 33, "Anvil Of Fury"},
    {ItemHelperType::Other, 34, "Book"},
    {ItemHelperType::Other, 35, "Book"},
    {ItemHelperType::Other, 36, "Book"},
    {ItemHelperType::Other, 37, "Fungal Tome"},
    {ItemHelperType::Other, 38, "Ring"},
    {ItemHelperType::Other, 39, "Ring"},
    {ItemHelperType::Other, 40, "Ring"},
    {ItemHelperType::Other, 41, "Ring"},
    {ItemHelperType::Other, 42, "Ring"},
    {ItemHelperType::Other, 43, "Amulet"},
    {ItemHelperType::Other, 44, "Amulet"},
    {ItemHelperType::Other, 45, "Amulet"},
    {ItemHelperType::Other, 46, "Sash"},
    {ItemHelperType::Other, 47, "Light Belt"},
    {ItemHelperType::Other, 48, "Belt"},
    {ItemHelperType::Other, 49, "Heavy Belt"},
    {ItemHelperType::Other, 50, "Plated Belt"},
    {ItemHelperType::Other, 51, "Cap"},
    {ItemHelperType::Other, 52, "Skull Cap"},
    {ItemHelperType::Other, 53, "Helm"},
    {ItemHelperType::Other, 54, "Full Helm"},
    {ItemHelperType::Other, 55, "Crown"},
    {ItemHelperType::Other, 56, "Great Helm"},
    {ItemHelperType::Other, 57, "Horned Helm"},
    {ItemHelperType::Other, 58, "Buckler"},
    {ItemHelperType::Other, 59, "Small Shield"},
    {ItemHelperType::Other, 60, "Large Shield"},
    {ItemHelperType::Other, 61, "Kite Shield"},
    {ItemHelperType::Other, 62, "Tower Shield"},
    {ItemHelperType::Other, 63, "Gothic Shield"},
    {ItemHelperType::Other, 64, "Rags"},
    {ItemHelperType::Other, 65, "Cape"},
    {ItemHelperType::Other, 66, "Cloak"},
    {ItemHelperType::Other, 67, "Robe"},
    {ItemHelperType::Other, 68, "Quilted Armor"},
    {ItemHelperType::Other, 69, "Leather Armor"},
    {ItemHelperType::Other, 70, "Hard Leather Armor"},
    {ItemHelperType::Other, 71, "Studded Leather Armor"},
    {ItemHelperType::Other, 72, "Ring Mail"},
    {ItemHelperType::Other, 73, "Chain Mail"},
    {ItemHelperType::Other, 74, "Scale Mail"},
    {ItemHelperType::Other, 75, "Split Mail"},
    {ItemHelperType::Other, 76, "Brest Plate"},
    {ItemHelperType::Other, 77, "Plate Mail"},
    {ItemHelperType::Other, 78, "Light Plate"},
    {ItemHelperType::Other, 79, "Gothic Plate"},
    {ItemHelperType::Other, 80, "Full Plate Mail"},
    {ItemHelperType::Other, 81, "Short Bow"},
    {ItemHelperType::Other, 82, "Hunter's Bow"},
    {ItemHelperType::Other, 83, "Long Bow"},
    {ItemHelperType::Other, 84, "Composite Bow"},
    {ItemHelperType::Other, 85, "Short Battle Bow"},
    {ItemHelperType::Other, 86, "Long Battle Bow"},
    {ItemHelperType::Other, 87, "Short War Bow"},
    {ItemHelperType::Other, 88, "Long War Bow"},
    {ItemHelperType::Other, 89, "Legacy Siege Bow"},
    {ItemHelperType::Other, 90, "Legacy Large Siege Bow"},
    {ItemHelperType::Other, 91, "Legacy Gothic Bow"},
    {ItemHelperType::Staff, 92, "Short Staff"},
    {ItemHelperType::Staff, 93, "Long Staff"},
    {ItemHelperType::Staff, 94, "Composite Staff"},
    {ItemHelperType::Staff, 95, "Quarter Staff"},
    {ItemHelperType::Staff, 96, "War Staff"},
    {ItemHelperType::Other, 97, "Club"},
    {ItemHelperType::Other, 98, "Spiked Club"},
    {ItemHelperType::Other, 99, "Mace"},
    {ItemHelperType::Other, 100, "Morning Star"},
    {ItemHelperType::Other, 101, "Flail"},
    {ItemHelperType::Other, 102, "War Hammer"},
    {ItemHelperType::Other, 103, "Scepter"},
    {ItemHelperType::Other, 104, "Maul"},
    {ItemHelperType::Other, 105, "Great Maul"},
    {ItemHelperType::Other, 106, "Small Axe"},
    {ItemHelperType::Other, 107, "Axe"},
    {ItemHelperType::Other, 108, "Large Axe"},
    {ItemHelperType::Other, 109, "Broad Axe"},
    {ItemHelperType::Other, 110, "Battle Axe"},
    {ItemHelperType::Other, 111, "Great Axe"},
    {ItemHelperType::Other, 112, "Giant Axe"},
    {ItemHelperType::Other, 113, "Dagger"},
    {ItemHelperType::Other, 114, "Small Sword"},
    {ItemHelperType::Other, 115, "Sabre"},
    {ItemHelperType::Other, 116, "Scimitar"},
    {ItemHelperType::Other, 117, "Blade"},
    {ItemHelperType::Other, 118, "Falchion"},
    {ItemHelperType::Other, 119, "Long Sword"},
    {ItemHelperType::Other, 120, "Claymore"},
    {ItemHelperType::Other, 121, "Broad Sword"},
    {ItemHelperType::Other, 122, "Bastard Sword"},
    {ItemHelperType::Other, 123, "Two Handed Sword"},
    {ItemHelperType::Other, 124, "Great Sword"},
    {ItemHelperType::Other, 125, "Cleaver"},
    {ItemHelperType::Other, 126, "Ring Mail"},
    {ItemHelperType::Other, 127, "Plate Mail"},
    {ItemHelperType::Other, 128, "Battle Axe"},
    {ItemHelperType::Other, 129, "Crossbow"},
    {ItemHelperType::Other, 130, "Flail"},
    {ItemHelperType::Other, 131, "Crow"},
    {ItemHelperType::Other, 132, "Executioner's Sword"},
    {ItemHelperType::Other, 133, "Horned Helm"},
    {ItemHelperType::Other, 134, "Helm"},
    {ItemHelperType::Other, 135, "Broad Sword"},
    {ItemHelperType::Other, 136, "Ancient Blade"},
    {ItemHelperType::Other, 137, "Maul"},
    {ItemHelperType::Other, 138, "Ancient Plate"},
    {ItemHelperType::Other, 139, "Hatchet"},
    {ItemHelperType::Other, 140, "Phase Blade"},
    {ItemHelperType::Other, 141, "Temple's Keystone"},
    {ItemHelperType::Other, 142, "Shadowfang"},
    {ItemHelperType::Other, 143, "Hellforge Hammer"},
    {ItemHelperType::Other, 144, "Treasure Map"},
    {ItemHelperType::Other, 145, "Symbol Of The Abandoned God"},
    {ItemHelperType::Other, 146, "Test Item"},
    {ItemHelperType::Other, 147, "Demonhide Shash"},
    {ItemHelperType::Other, 148, "Sharkskin Belt"},
    {ItemHelperType::Other, 149, "Mesh Belt"},
    {ItemHelperType::Other, 150, "Battle Belt"},
    {ItemHelperType::Other, 151, "War Belt"},
    {ItemHelperType::Other, 152, "War Hat"},
    {ItemHelperType::Other, 153, "Sallet"},
    {ItemHelperType::Other, 154, "Barbute"},
    {ItemHelperType::Other, 155, "Visor"},
    {ItemHelperType::Other, 156, "Grand Crown"},
    {ItemHelperType::Other, 157, "Ancient Helm"},
    {ItemHelperType::Other, 158, "Spired Helm"},
    {ItemHelperType::Other, 159, "Defender"},
    {ItemHelperType::Other, 160, "Round Shield"},
    {ItemHelperType::Other, 161, "Dragon Shield"},
    {ItemHelperType::Other, 162, "Monarch"},
    {ItemHelperType::Other, 163, "Ward"},
    {ItemHelperType::Other, 164, "Aegis"},
    {ItemHelperType::Other, 165, "Tatters"},
    {ItemHelperType::Other, 166, "Mantle"},
    {ItemHelperType::Other, 167, "Shroud"},
    {ItemHelperType::Other, 168, "Grand Robe"},
    {ItemHelperType::Other, 169, "Serpentskin Armor"},
    {ItemHelperType::Other, 170, "Demonhide Armor"},
    {ItemHelperType::Other, 171, "Wyrmhide Armor"},
    {ItemHelperType::Other, 172, "Dragonhide Armor"},
    {ItemHelperType::Other, 173, "Linked Mail"},
    {ItemHelperType::Other, 174, "Mesh Armor"},
    {ItemHelperType::Other, 175, "Hauberk"},
    {ItemHelperType::Other, 176, "Tigulated Mail"},
    {ItemHelperType::Other, 177, "Cuirass"},
    {ItemHelperType::Other, 178, "Templar Plate"},
    {ItemHelperType::Other, 179, "Archon Plate"},
    {ItemHelperType::Other, 180, "Ornate Plate"},
    {ItemHelperType::Other, 181, "Ancient Plate"},
    {ItemHelperType::Other, 182, "Edge Bow"},
    {ItemHelperType::Other, 183, "Razor Bow"},
    {ItemHelperType::Other, 184, "Cedar Bow"},
    {ItemHelperType::Other, 185, "Ward Bow"},
    {ItemHelperType::Other, 186, "Short Siege Bow"},
    {ItemHelperType::Other, 187, "Long Siege Bow"},
    {ItemHelperType::Other, 188, "Rune Bow"},
    {ItemHelperType::Other, 189, "Gothic Bow"},
    {ItemHelperType::Staff, 190, "Elder Staff"},
    {ItemHelperType::Staff, 191, "Cedar Staff"},
    {ItemHelperType::Staff, 192, "Gothic Staff"},
    {ItemHelperType::Staff, 193, "Rune Staff"},
    {ItemHelperType::Staff, 194, "Archon Staff"},
    {ItemHelperType::Other, 195, "Cudgel"},
    {ItemHelperType::Other, 196, "Barbed Club"},
    {ItemHelperType::Other, 197, "Flanged Mace"},
    {ItemHelperType::Other, 198, "Jagged Star"},
    {ItemHelperType::Other, 199, "Knout"},
    {ItemHelperType::Other, 200, "Battle Hammer"},
    {ItemHelperType::Other, 201, "Divine Scepter"},
    {ItemHelperType::Other, 202, "War Maul"},
    {ItemHelperType::Other, 203, "Martel De Fer"},
    {ItemHelperType::Other, 204, "Cleaver"},
    {ItemHelperType::Other, 205, "Military Axe"},
    {ItemHelperType::Other, 206, "Twin Axe"},
    {ItemHelperType::Other, 207, "Bearded Axe"},
    {ItemHelperType::Other, 208, "Tabar"},
    {ItemHelperType::Other, 209, "Gothic Axe"},
    {ItemHelperType::Other, 210, "Ancient Axe"},
    {ItemHelperType::Other, 211, "Bone Knife"},
    {ItemHelperType::Other, 212, "Gladius"},
    {ItemHelperType::Other, 213, "Rapier"},
    {ItemHelperType::Other, 214, "Cutlass"},
    {ItemHelperType::Other, 215, "Backsword"},
    {ItemHelperType::Other, 216, "Tulwar"},
    {ItemHelperType::Other, 217, "Espadon"},
    {ItemHelperType::Other, 218, "Battle Sword"},
    {ItemHelperType::Other, 219, "Rune Sword"},
    {ItemHelperType::Other, 220, "Ancient Sword"},
    {ItemHelperType::Other, 221, "Colossal Blade"},
    {ItemHelperType::Other, 222, "Executioner's Sword"},
    {ItemHelperType::Other, 223, "Executioner's Sword"},
    {ItemHelperType::Other, 224, "Claw"},
    {ItemHelperType::Other, 225, "Artifact"},
    {ItemHelperType::Other, 226, "Grim Helm"},
    {ItemHelperType::Other, 227, "Corona"},
    {ItemHelperType::Other, 228, "Hand Crossbow"},
    {ItemHelperType::Other, 229, "Siege Crossbow"},
    {ItemHelperType::Other, 230, "Swirling Crystal"},
    {ItemHelperType::Other, 231, "Dimensional Shard"},
    {ItemHelperType::Other, 232, "Ring"},
    {ItemHelperType::Other, 233, "Ring"},
    {ItemHelperType::Other, 234, "Amulet"},
    {ItemHelperType::Other, 235, "Amulet"},
    {ItemHelperType::Other, 236, "Amulet"},
    {ItemHelperType::Other, 237, "Sheet"},
    {ItemHelperType::Other, 238, "Gem"},
    {ItemHelperType::Other, 239, "Rune"},
    {ItemHelperType::Other, 240, "Oil"},
    {ItemHelperType::Other, 241, "Sheet"},
    {ItemHelperType::Other, 242, "Wrist Blade"},
    {ItemHelperType::Other, 243, "Wrist Spike"},
};

}

#endif // ITEMTYPE_H
