#ifndef RECIPE_H
#define RECIPE_H

#include <vector>
#include <string>
#include <map>

namespace Belzebub {

enum class RecipeType : int {
    TransmuteRegularGem = 26294,
    TransmuteFlawlessGem,
    UpgradeMagicArmor, UpgradeCraftedArmor, UpgradeRareArmor, UpgradeSetArmor, UpgradeUniqueArmor,
    UpgradeMagicWeapon, UpgradeCraftedWeapon, UpgradeRareWeapon, UpgradeSetWeapon, UpgradeUniqueWeapon,
    WarriorsWeapon, WarriorsRing, WarriorsAmulet, WarriorsHelm, WarriorsMail, WarriorsBelt, WarriorsShield,
    ChampionsWeapon, ChampionsRing, ChampionsAmulet, ChampionsHelm, ChampionsPlate, ChampionsBelt, ChampionsShield,
    WarlordsWeapon, WarlordsRing, WarlordsAmulet, WarlordsHelm, WarlordsPlate, WarlordsBelt, WarlordsShield,
    GuardiansWeapon, GuardiansRing, GuardiansAmulet, GuardiansHelm, GuardiansPlate, GuardiansBelt, GuardiansShield,
    RoguesWeapon, RoguesRing, RoguesAmulet, RoguesHelm, RoguesMail, RoguesBelt, RoguesBow,
    ScoutsWeapon, ScoutsRing, ScoutsAmulet, ScoutsHelm, ScoutsMail, ScoutsBelt, ScoutsBow,
    StalkersWeapon, StalkersRing, StalkersAmulet, StalkersHelm, StalkersMail, StalkersBelt, StalkersBow,
    HarbingersWeapon, HarbingersRing, HarbingersAmulet, HarbingersHelm, HarbingersMail, HarbingersBelt, HarbingersBow,
    BarbariansWeapon, BarbariansRing, BarbariansAmulet, BarbariansHelm, BarbariansMail, BarbariansBelt,
    HighlandersWeapon, HighlandersRing, HighlandersAmulet, HighlandersHelm, HighlandersPlate, HighlandersBelt,
    ReaversWeapon, ReaversRing, ReaversAmulet, ReaversHelm, ReaversPlate, ReaversBelt,
    ConquerorsWeapon, ConquerorsRing, ConquerorsAmulet, ConquerorsHelm, ConquerorsPlate, ConquerorsBelt,
    SorcerersStaff, SorcerersRing, SorcerersAmulet, SorcerersHelm, SorcerersArmor, SorcerersBelt,
    WizardsStaff, WizardsRing, WizardsAmulet, WizardsHelm, WizardsArmor, WizardsBelt,
    MagesStaff, MagesRing, MagesAmulet, MagesHelm, MagesArmor, MagesBelt,
    ArchMagesStaff, ArchMagesRing, ArchMagesAmulet, ArchMagesHelm, ArchMagesArmor, ArchMagesBelt,
    DisciplesStaff, DisciplesRing, DisciplesAmulet, DisciplesHelm, DisciplesArmor, DisciplesBelt,
    EnchantersStaff, EnchantersRing, EnchantersAmulet, EnchantersHelm, EnchantersArmor, EnchantersBelt,
    ConjurorsStaff, ConjurorsRing, ConjurorsAmulet, ConjurorsHelm, ConjurorsArmor, ConjurorsBelt,
    SpellweaversStaff, SpellweaversRing, SpellweaversAmulet, SpellweaversHelm, SpellweaversArmor, SpellweaversBelt,
    BlazingArmor, BlazingHelm, BlazingBelt, BlazingShield,
    VolcanicArmor, VolcanicHelm, VolcanicBelt, VolcanicShield,
    SparklingArmor, SparklingHelm, SparklingBelt, SparklingShield,
    ChargedArmor, ChargedHelm, ChargedBelt, ChargedShield,
    FreezingArmor, FreezingHelm, FreezingBelt, FreezingShield,
    GlacialArmor, GlacialHelm, GlacialBelt, GlacialShield,
    BrilliantArmor, BrilliantHelm, BrilliantBelt, BrilliantShield,
    RadiantArmor, RadiantHelm, RadiantBelt, RadiantShield,
    NecromancersStaff, NecromancersRing, NecromancersAmulet, NecromancersHelm, NecromancersArmor, NecromancersBelt,
    CallersStaff, CallersRing, CallersAmulet, CallersHelm, CallersArmor, CallersBelt,
    SummonersStaff, SummonersRing, SummonersAmulet, SummonersHelm, SummonersArmor, SummonersBelt,
    RitualistsStaff, RitualistsRing, RitualistsAmulet, RitualistsHelm, RitualistsArmor, RitualistsBelt,
    AssassinsWeapon, AssassinsRing, AssassinsAmulet, AssassinsHelm, AssassinsArmor, AssassinsBelt,
    ThiefsWeapon, ThiefsRing, ThiefsAmulet, ThiefsHelm, ThiefsArmor, ThiefsBelt,
    ZealotsWeapon, ZealotsRing, ZealotsAmulet, ZealotsHelm, ZealotsMail, ZealotsBelt,
    FanaticsWeapon, FanaticsRing, FanaticsAmulet, FanaticsHelm, FanaticsArmor, FanaticsBelt,
    HardenedIronRing, DragonslayersHauberk, SealOfSlaughter, TheEyeOfTheStorm, HandOfJustice,
    End
};
const std::map<RecipeType, std::string> recipeNames = {
    {RecipeType::TransmuteRegularGem, "Transmute Regular Gem"},
    {RecipeType::TransmuteFlawlessGem, "Transmute Flawless Gem"},
    {RecipeType::UpgradeMagicArmor, "Upgrade Magic Armor"},
    {RecipeType::UpgradeCraftedArmor, "Upgrade Crafted Armor"},
    {RecipeType::UpgradeRareArmor, "Upgrade Rare Armor"},
    {RecipeType::UpgradeSetArmor, "Upgrade Set Armor"},
    {RecipeType::UpgradeUniqueArmor, "Upgrade Unique Armor"},
    {RecipeType::UpgradeMagicWeapon, "Upgrade Magic Weapon"},
    {RecipeType::UpgradeCraftedWeapon, "Upgrade Crafted Weapon"},
    {RecipeType::UpgradeRareWeapon, "Upgrade Rare Weapon"},
    {RecipeType::UpgradeSetWeapon, "Upgrade Set Weapon"},
    {RecipeType::UpgradeUniqueWeapon, "Upgrade Unique Weapon"},
    {RecipeType::WarriorsWeapon, "Warrior's Weapon"},
    {RecipeType::WarriorsRing, "Warrior's Ring"},
    {RecipeType::WarriorsAmulet, "Warrior's Amulet"},
    {RecipeType::WarriorsHelm, "Warrior's Helm"},
    {RecipeType::WarriorsMail, "Warrior's Mail"},
    {RecipeType::WarriorsBelt, "Warrior's Belt"},
    {RecipeType::WarriorsShield, "Warrior's Shield"},
    {RecipeType::ChampionsWeapon, "Champion's Weapon"},
    {RecipeType::ChampionsRing, "Champion's Ring"},
    {RecipeType::ChampionsAmulet, "Champion's Amulet"},
    {RecipeType::ChampionsHelm, "Champion's Helm"},
    {RecipeType::ChampionsPlate, "Champion's Plate"},
    {RecipeType::ChampionsBelt, "Champion's Belt"},
    {RecipeType::ChampionsShield, "Champion's Shield"},
    {RecipeType::WarlordsWeapon, "Warlord's Weapon"},
    {RecipeType::WarlordsRing, "Warlord's Ring"},
    {RecipeType::WarlordsAmulet, "Warlord's Amulet"},
    {RecipeType::WarlordsHelm, "Warlord's Helm"},
    {RecipeType::WarlordsPlate, "Warlord's Plate"},
    {RecipeType::WarlordsBelt, "Warlord's Belt"},
    {RecipeType::WarlordsShield, "Warlord's Shield"},
    {RecipeType::GuardiansWeapon, "Guardian's Weapon"},
    {RecipeType::GuardiansRing, "Guardian's Ring"},
    {RecipeType::GuardiansAmulet, "Guardian's Amulet"},
    {RecipeType::GuardiansHelm, "Guardian's Helm"},
    {RecipeType::GuardiansPlate, "Guardian's Plate"},
    {RecipeType::GuardiansBelt, "Guardian's Belt"},
    {RecipeType::GuardiansShield, "Guardian's Shield"},
    {RecipeType::RoguesWeapon, "Rogue's Weapon"},
    {RecipeType::RoguesRing, "Rogue's Ring"},
    {RecipeType::RoguesAmulet, "Rogue's Amulet"},
    {RecipeType::RoguesHelm, "Rogue's Helm"},
    {RecipeType::RoguesMail, "Rogue's Mail"},
    {RecipeType::RoguesBelt, "Rogue's Belt"},
    {RecipeType::RoguesBow, "Rogue's Bow"},
    {RecipeType::ScoutsWeapon, "Scout's Weapon"},
    {RecipeType::ScoutsRing, "Scout's Ring"},
    {RecipeType::ScoutsAmulet, "Scout's Amulet"},
    {RecipeType::ScoutsHelm, "Scout's Helm"},
    {RecipeType::ScoutsMail, "Scout's Mail"},
    {RecipeType::ScoutsBelt, "Scout's Belt"},
    {RecipeType::ScoutsBow, "Scout's Bow"},
    {RecipeType::StalkersWeapon, "Stalker's Weapon"},
    {RecipeType::StalkersRing, "Stalker's Ring"},
    {RecipeType::StalkersAmulet, "Stalker's Amulet"},
    {RecipeType::StalkersHelm, "Stalker's Helm"},
    {RecipeType::StalkersMail, "Stalker's Mail"},
    {RecipeType::StalkersBelt, "Stalker's Belt"},
    {RecipeType::StalkersBow, "Stalker's Bow"},
    {RecipeType::HarbingersWeapon, "Harbinger's Weapon"},
    {RecipeType::HarbingersRing, "Harbinger's Ring"},
    {RecipeType::HarbingersAmulet, "Harbinger's Amulet"},
    {RecipeType::HarbingersHelm, "Harbinger's Helm"},
    {RecipeType::HarbingersMail, "Harbinger's Mail"},
    {RecipeType::HarbingersBelt, "Harbinger's Belt"},
    {RecipeType::HarbingersBow, "Harbinger's Bow"},
    {RecipeType::BarbariansWeapon, "Barbarian's Weapon"},
    {RecipeType::BarbariansRing, "Barbarian's Ring"},
    {RecipeType::BarbariansAmulet, "Barbarian's Amulet"},
    {RecipeType::BarbariansHelm, "Barbarian's Helm"},
    {RecipeType::BarbariansMail, "Barbarian's Mail"},
    {RecipeType::BarbariansBelt, "Barbarian's Belt"},
    {RecipeType::HighlandersWeapon, "Highlander's Weapon"},
    {RecipeType::HighlandersRing, "Highlander's Ring"},
    {RecipeType::HighlandersAmulet, "Highlander's Amulet"},
    {RecipeType::HighlandersHelm, "Highlander's Helm"},
    {RecipeType::HighlandersPlate, "Highlander's Plate"},
    {RecipeType::HighlandersBelt, "Highlander's Belt"},
    {RecipeType::ReaversWeapon, "Reaver's Weapon"},
    {RecipeType::ReaversRing, "Reaver's Ring"},
    {RecipeType::ReaversAmulet, "Reaver's Amulet"},
    {RecipeType::ReaversHelm, "Reaver's Helm"},
    {RecipeType::ReaversPlate, "Reaver's Plate"},
    {RecipeType::ReaversBelt, "Reaver's Belt"},
    {RecipeType::ConquerorsWeapon, "Conqueror's Weapon"},
    {RecipeType::ConquerorsRing, "Conqueror's Ring"},
    {RecipeType::ConquerorsAmulet, "Conqueror's Amulet"},
    {RecipeType::ConquerorsHelm, "Conqueror's Helm"},
    {RecipeType::ConquerorsPlate, "Conqueror's Plate"},
    {RecipeType::ConquerorsBelt, "Conqueror's Belt"},
    {RecipeType::SorcerersStaff, "Sorcerer's Staff"},
    {RecipeType::SorcerersRing, "Sorcerer's Ring"},
    {RecipeType::SorcerersAmulet, "Sorcerer's Amulet"},
    {RecipeType::SorcerersHelm, "Sorcerer's Helm"},
    {RecipeType::SorcerersArmor, "Sorcerer's Armor"},
    {RecipeType::SorcerersBelt, "Sorcerer's Belt"},
    {RecipeType::WizardsStaff, "Wizard's Staff"},
    {RecipeType::WizardsRing, "Wizard's Ring"},
    {RecipeType::WizardsAmulet, "Wizard's Amulet"},
    {RecipeType::WizardsHelm, "Wizard's Helm"},
    {RecipeType::WizardsArmor, "Wizard's Armor"},
    {RecipeType::WizardsBelt, "Wizard's Belt"},
    {RecipeType::MagesStaff, "Mage's Staff"},
    {RecipeType::MagesRing, "Mage's Ring"},
    {RecipeType::MagesAmulet, "Mage's Amulet"},
    {RecipeType::MagesHelm, "Mage's Helm"},
    {RecipeType::MagesArmor, "Mage's Armor"},
    {RecipeType::MagesBelt, "Mage's Belt"},
    {RecipeType::ArchMagesStaff, "Arch-Mage's Staff"},
    {RecipeType::ArchMagesRing, "Arch-Mage's Ring"},
    {RecipeType::ArchMagesAmulet, "Arch-Mage's Amulet"},
    {RecipeType::ArchMagesHelm, "Arch-Mage's Helm"},
    {RecipeType::ArchMagesArmor, "Arch-Mage's Armor"},
    {RecipeType::ArchMagesBelt, "Arch-Mage's Belt"},
    {RecipeType::DisciplesStaff, "Disciple's Staff"},
    {RecipeType::DisciplesRing, "Disciple's Ring"},
    {RecipeType::DisciplesAmulet, "Disciple's Amulet"},
    {RecipeType::DisciplesHelm, "Disciple's Helm"},
    {RecipeType::DisciplesArmor, "Disciple's Armor"},
    {RecipeType::DisciplesBelt, "Disciple's Belt"},
    {RecipeType::EnchantersStaff, "Enchanter's Staff"},
    {RecipeType::EnchantersRing, "Enchanter's Ring"},
    {RecipeType::EnchantersAmulet, "Enchanter's Amulet"},
    {RecipeType::EnchantersHelm, "Enchanter's Helm"},
    {RecipeType::EnchantersArmor, "Enchanter's Armor"},
    {RecipeType::EnchantersBelt, "Enchanter's Belt"},
    {RecipeType::ConjurorsStaff, "Conjuror's Staff"},
    {RecipeType::ConjurorsRing, "Conjuror's Ring"},
    {RecipeType::ConjurorsAmulet, "Conjuror's Amulet"},
    {RecipeType::ConjurorsHelm, "Conjuror's Helm"},
    {RecipeType::ConjurorsArmor, "Conjuror's Armor"},
    {RecipeType::ConjurorsBelt, "Conjuror's Belt"},
    {RecipeType::SpellweaversStaff, "Spellweaver's Staff"},
    {RecipeType::SpellweaversRing, "Spellweaver's Ring"},
    {RecipeType::SpellweaversAmulet, "Spellweaver's Amulet"},
    {RecipeType::SpellweaversHelm, "Spellweaver's Helm"},
    {RecipeType::SpellweaversArmor, "Spellweaver's Armor"},
    {RecipeType::SpellweaversBelt, "Spellweaver's Belt"},
    {RecipeType::BlazingArmor, "Blazing Armor"},
    {RecipeType::BlazingHelm, "Blazing Helm"},
    {RecipeType::BlazingBelt, "Blazing Belt"},
    {RecipeType::BlazingShield, "Blazing Shield"},
    {RecipeType::VolcanicArmor, "Volcanic Armor"},
    {RecipeType::VolcanicHelm, "Volcanic Helm"},
    {RecipeType::VolcanicBelt, "Volcanic Belt"},
    {RecipeType::VolcanicShield, "VolcanicShield"},
    {RecipeType::SparklingArmor, "Sparkling Armor"},
    {RecipeType::SparklingHelm, "Sparkling Helm"},
    {RecipeType::SparklingBelt, "Sparkling Belt"},
    {RecipeType::SparklingShield, "Sparkling Shield"},
    {RecipeType::ChargedArmor, "Charged Armor"},
    {RecipeType::ChargedHelm, "Charged Helm"},
    {RecipeType::ChargedBelt, "Charged Belt"},
    {RecipeType::ChargedShield, "Charged Shield"},
    {RecipeType::FreezingArmor, "Freezing Armor"},
    {RecipeType::FreezingHelm, "Freezing Helm"},
    {RecipeType::FreezingBelt, "Freezing Belt"},
    {RecipeType::FreezingShield, "Freezing Shield"},
    {RecipeType::GlacialArmor, "Glacial Armor"},
    {RecipeType::GlacialHelm, "Glacial Helm"},
    {RecipeType::GlacialBelt, "Glacial Belt"},
    {RecipeType::GlacialShield, "Glacial Shield"},
    {RecipeType::BrilliantArmor, "Brilliant Armor"},
    {RecipeType::BrilliantHelm, "Brilliant Helm"},
    {RecipeType::BrilliantBelt, "Brilliant Belt"},
    {RecipeType::BrilliantShield, "Brilliant Shield"},
    {RecipeType::RadiantArmor, "Radiant Armor"},
    {RecipeType::RadiantHelm, "Radiant Helm"},
    {RecipeType::RadiantBelt, "Radiant Belt"},
    {RecipeType::RadiantShield, "Radiant Shield"},
    {RecipeType::NecromancersStaff, "Necromancer's Staff"},
    {RecipeType::NecromancersRing, "Necromancer's Ring"},
    {RecipeType::NecromancersAmulet, "Necromancer's Amulet"},
    {RecipeType::NecromancersHelm, "Necromancer's Helm"},
    {RecipeType::NecromancersArmor, "Necromancer's Armor"},
    {RecipeType::NecromancersBelt, "Necromancer's Belt"},
    {RecipeType::CallersStaff, "Caller's Staff"},
    {RecipeType::CallersRing, "Caller's Ring"},
    {RecipeType::CallersAmulet, "Caller's Amulet"},
    {RecipeType::CallersHelm, "Caller's Helm"},
    {RecipeType::CallersArmor, "Caller's Armor"},
    {RecipeType::CallersBelt, "Caller's Belt"},
    {RecipeType::SummonersStaff, "Summoner's Staff"},
    {RecipeType::SummonersRing, "Summoner's Ring"},
    {RecipeType::SummonersAmulet, "Summoner's Amulet"},
    {RecipeType::SummonersHelm, "Summoner's Helm"},
    {RecipeType::SummonersArmor, "Summoner's Armor"},
    {RecipeType::SummonersBelt, "Summoner's Belt"},
    {RecipeType::RitualistsStaff, "Ritualist's Staff"},
    {RecipeType::RitualistsRing, "Ritualist's Ring"},
    {RecipeType::RitualistsAmulet, "Ritualist's Amulet"},
    {RecipeType::RitualistsHelm, "Ritualist's Helm"},
    {RecipeType::RitualistsArmor, "Ritualist's Armor"},
    {RecipeType::RitualistsBelt, "Ritualist's Belt"},
    {RecipeType::AssassinsWeapon, "Assassin's Weapon"},
    {RecipeType::AssassinsRing, "Assassin's Ring"},
    {RecipeType::AssassinsAmulet, "Assassin's Amulet"},
    {RecipeType::AssassinsHelm, "Assassin's Helm"},
    {RecipeType::AssassinsArmor, "Assassin's Armor"},
    {RecipeType::AssassinsBelt, "Assassin's Belt"},
    {RecipeType::ThiefsWeapon, "Thief's Weapon"},
    {RecipeType::ThiefsRing, "Thief's Ring"},
    {RecipeType::ThiefsAmulet, "Thief's Amulet"},
    {RecipeType::ThiefsHelm, "Thief's Helm"},
    {RecipeType::ThiefsArmor, "Thief's Armor"},
    {RecipeType::ThiefsBelt, "Thief's Belt"},
    {RecipeType::ZealotsWeapon, "Zealot's Weapon"},
    {RecipeType::ZealotsRing, "Zealot's Ring"},
    {RecipeType::ZealotsAmulet, "Zealot's Amulet"},
    {RecipeType::ZealotsHelm, "Zealot's Helm"},
    {RecipeType::ZealotsMail, "Zealot's Mail"},
    {RecipeType::ZealotsBelt, "Zealot's Belt"},
    {RecipeType::FanaticsWeapon, "Fanatic's Weapon"},
    {RecipeType::FanaticsRing, "Fanatic's Ring"},
    {RecipeType::FanaticsAmulet, "Fanatic's Amulet"},
    {RecipeType::FanaticsHelm, "Fanatic's Helm"},
    {RecipeType::FanaticsArmor, "Fanatic's Armor"},
    {RecipeType::FanaticsBelt, "Fanatic's Belt"},
    {RecipeType::HardenedIronRing, "Hardened Iron Ring"},
    {RecipeType::DragonslayersHauberk, "Dragonslayer's Hauberk"},
    {RecipeType::SealOfSlaughter, "Seal Of Slaughter"},
    {RecipeType::TheEyeOfTheStorm, "The Eye Of The Storm"},
    {RecipeType::HandOfJustice, "Hand Of Justice"}
};

}

#endif // RECIPE_H
